#!/bin/bash

# INPUT:
# resources/fithichip_config_file

# OUTPUT:
# results/${sample}.interactions_FitHiC_Q0.01_IGV.bedpe

# Source conda environment
eval "$(conda shell.bash hook)" 
conda activate hichip_conda_environment

# Run Fithichip
# Uses the FitHiChIP_HiCPro.sh script obtained from downloading and compiling Fithichip software from the github repo
# https://github.com/ay-lab/FitHiChIP/tree/master
bash ./FitHiChIP_HiCPro.sh -C resources/fithichip_config_file

# Move relevant results file out of very nested directory structure generated by fithichip
mv results/${sample}_fithichip_loops/FitHiChIP_Peak2ALL_b5000_L5000_U2000000/P2PBckgr_0/Coverage_Bias/FitHiC_BiasCorr/${sample}.interactions_FitHiC_Q0.01_IGV.bedpe results
